
name: Dzialki

description: Dzialki do MC 1.6.4

author: wiktorek140
website: 

main: org.wiktorek140.Dzialka

version: 0.1-SNAPSHOT

commands:
    dzialka:
        description: Tworzenie dzialek
        permission: dzialka.admin
        usage: /dzialka help

soft-depend: [SQLibrary, Vault, WorldGuard, Factions]

permissions:
    dzialka.*:
        default: true
        children:
            dzialka.tworzenie: true
            dzialka.tworzenieV: false
            dzialka.tworzenieS: false
            dzialka.zarzadzanie: true
    dzialka.zarzadzanie:
        default: false
        description: Usuwanie dzialek
    dzialka.tworzenie:
        default: false
        description: Pozwala tworzyc dzialke
    dzialka.tworzenieV:
        default: false
        description: Pozwala tworzyc dzialki vip-om
    dzialka.tworzenieS:
        default: false
        description: Pozwala tworzyc dzialki supervipom
